import { Strain } from "@/types";
import { createStrain } from "./iconGenerator";
import { writeStrainJSON } from "./strainJSONWriter";

export const DEMO_STRAINS_DATA = [
  { name: "Blue Dream", type: "hybrid" as const, terp_profile: ["myrcene" as const, "pinene" as const], description: "Lineage: Blueberry x Haze. Balanced hybrid with sweet berry notes; smooth uplift with calm body ease." },
  { name: "Northern Lights", type: "indica" as const, terp_profile: ["pinene" as const, "myrcene" as const], description: "Lineage: Afghani landrace lineage. Classic indica known for deep, serene body calm and pine-leaning aroma." },
  { name: "Sour Diesel", type: "sativa" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Chemdawg x Super Skunk. Pungent, citrus-diesel profile with fast, hazy head lift." },
  { name: "Girl Scout Cookies", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: OG Kush x Durban Poison. Sweet dough and earth; euphoric, cozy hybrid." },
  { name: "OG Kush", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chemdawg family. Iconic gas and pine; comfortable, heavy-lidded hybrid." },
  { name: "Granddaddy Purple", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Purple Urkle x Big Bud. Grape-berry bouquet; full-body, soothing indica feel." },
  { name: "Gelato", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Sunset Sherbet x Thin Mint Cookies. Dessert-sweet, creamy; relaxed euphoria." },
  { name: "Wedding Cake", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Triangle Kush x Animal Mints. Frosted vanilla cookie aroma; calm, content hybrid." },
  { name: "Pineapple Express", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: Trainwreck x Hawaiian. Tropical citrus with breezy, upbeat feel." },
  { name: "Durban Poison", type: "sativa" as const, terp_profile: ["pinene" as const, "limonene" as const], description: "Lineage: South African landrace. Bright anise-citrus; focused, active sativa character." },
  { name: "Jack Herer", type: "sativa" as const, terp_profile: ["pinene" as const, "myrcene" as const], description: "Lineage: Haze hybrid family. Pine, citrus, spice; uplifted clarity and creativity." },
  { name: "Super Lemon Haze", type: "sativa" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Lemon Skunk x Super Silver Haze. Zesty lemon candy with buoyant energy." },
  { name: "AK-47", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: Mixed landraces. Floral-earth and spice; mellow, balanced headspace." },
  { name: "Trainwreck", type: "hybrid" as const, terp_profile: ["pinene" as const, "myrcene" as const], description: "Lineage: Mexican x Thai x Afghani. Piney, lemon spice; surging head-high with warm body melt." },
  { name: "Bubba Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: Kush family. Coffee-chocolate earth; deeply settling indica." },
  { name: "Skywalker OG", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: Skywalker x OG Kush. Spiced pine and gas; weighty, spacey calm." },
  { name: "Gorilla Glue #4", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Chem's Sister x Sour Dubb x Chocolate Diesel. Earthy glue and gas; heavy, couchy hybrid." },
  { name: "Sunset Sherbet", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Girl Scout Cookies x Pink Panties. Fruity sherbet; mellow, dreamy mood." },
  { name: "Strawberry Cough", type: "sativa" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Strawberry fields lineage. Fresh strawberry sweet; airy, sociable lift." },
  { name: "Cherry Pie", type: "hybrid" as const, terp_profile: ["linalool" as const, "caryophyllene" as const], description: "Lineage: Granddaddy Purple x F1 Durb. Tart cherry pastry; calm and cheerful." },
  { name: "Purple Haze", type: "sativa" as const, terp_profile: ["myrcene" as const, "pinene" as const], description: "Lineage: Haze family. Sweet berry-floral; buzzy, colorful headspace." },
  { name: "Green Crack", type: "sativa" as const, terp_profile: ["myrcene" as const, "limonene" as const], description: "Lineage: Skunk #1 family. Mango-citrus snap; bright, zippy momentum." },
  { name: "White Widow", type: "hybrid" as const, terp_profile: ["pinene" as const, "myrcene" as const], description: "Lineage: Brazilian sativa x South Indian indica. Pungent pine; balanced, social hybrid." },
  { name: "Alien OG", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Tahoe OG x Alien Kush. Citrus-pine gas; potent, spacey calm." },
  { name: "Tahoe OG", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: OG Kush family. Lemon-pine OG profile; thorough evening comfort." },
  { name: "Purple Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Hindu Kush x Purple Afghani. Grape-berry and earth; tranquil body calm." },
  { name: "Banana Kush", type: "hybrid" as const, terp_profile: ["myrcene" as const, "limonene" as const], description: "Lineage: Ghost OG x Skunk Haze. Creamy banana and citrus; relaxed, content hybrid." },
  { name: "Mango Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "limonene" as const], description: "Lineage: KC33 x Afghani. Ripe mango and tropical sweetness; cozy, soothing body feel." },
  { name: "Zkittlez", type: "hybrid" as const, terp_profile: ["humulene" as const, "caryophyllene" as const], description: "Lineage: Grape Ape x Grapefruit. Rainbow candy; calm, happy hybrid mood." },
  { name: "Runtz", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Zkittlez x Gelato. Sugary fruit; even-keeled, blissful hybrid." },
  { name: "Ice Cream Cake", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Wedding Cake x Gelato #33. Frosted vanilla and dough; peaceful, heavy indica lean." },
  { name: "Lemon Haze", type: "sativa" as const, terp_profile: ["limonene" as const, "pinene" as const], description: "Lineage: Lemon Skunk x Silver Haze. Bright lemon peel; lively, chatty uplift." },
  { name: "Orange Cookies", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Orange Juice x GSC. Tangy orange dough; cheerful, calm balance." },
  { name: "Apple Fritter", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "linalool" as const], description: "Lineage: Sour Apple x Animal Cookies. Baked apple and spice; cozy, dreamy hybrid." },
  { name: "Do-Si-Dos", type: "indica" as const, terp_profile: ["caryophyllene" as const, "linalool" as const], description: "Lineage: Girl Scout Cookies x Face Off OG. Cookie dough and floral spice; deep, tranquil calm." },
  { name: "Bruce Banner", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: OG Kush x Strawberry Diesel. Strawberry-diesel; strong, expansive hybrid lift." },
  { name: "Chemdawg", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chem family. Pungent chem and gas; potent, thought-forward hybrid." },
  { name: "GSC Thin Mint", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: GSC phenotype. Minty-cookie sweetness; buoyant, soothing hybrid." },
  { name: "Super Silver Haze", type: "sativa" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Skunk x Northern Lights x Haze. Metallic citrus haze; bright, long-lasting head buzz." },
  { name: "Grape Ape", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Mendocino Purps x Skunk x Afghani. Grape candy and earth; restful couchy feel." },
  { name: "Forbidden Fruit", type: "indica" as const, terp_profile: ["linalool" as const, "myrcene" as const], description: "Lineage: Cherry Pie x Tangie. Exotic tropical citrus; serene, lazy calm." },
  { name: "Tangie", type: "sativa" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: California Orange x Skunk. Fresh tangerine zest; buoyant, creative focus." },
  { name: "LA Confidential", type: "indica" as const, terp_profile: ["myrcene" as const, "pinene" as const], description: "Lineage: OG LA Affie x Afghani. Forest pine and earth; heavy-bodied calm." },
  { name: "Blueberry", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Afghani x Thai x Purple Thai. Sweet blueberry; tranquil, content body feel." },
  { name: "Amnesia Haze", type: "sativa" as const, terp_profile: ["limonene" as const, "pinene" as const], description: "Lineage: Haze family blend. Citrus-herbal haze; bright, soaring headspace." },
  { name: "Platinum Cookies", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: OG Kush x Durban Poison x Cherry Kush. Sweet berry-cookie; mellow, euphoric feel." },
  { name: "Fire OG", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: OG Kush x SFV OG. Lemon gas with earth; potent, sedative hybrid." },
  { name: "Death Star", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: Sensi Star x Sour Diesel. Jet fuel and skunk; heavy, cosmic body high." },
  { name: "Headband", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: OG Kush x Sour Diesel. Lemon diesel; smooth headband pressure, mellow focus." },
  { name: "Silver Haze", type: "sativa" as const, terp_profile: ["pinene" as const, "limonene" as const], description: "Lineage: Original Haze. Spicy citrus haze; clear-headed, energetic buzz." },
  { name: "Pink Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: OG Kush variant. Floral candy sweetness; sedating, body-melting calm." },
  { name: "Clementine", type: "sativa" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: Tangie x Lemon Skunk. Citrus burst; uplifting, creative energy." },
  { name: "Mimosa", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Clementine x Purple Punch. Tropical citrus champagne; happy, relaxed vibe." },
  { name: "Purple Punch", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: Larry OG x Granddaddy Purple. Grape candy and berry; dreamy nighttime sedation." },
  { name: "Wedding Crasher", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Wedding Cake x Purple Punch. Vanilla berry cream; blissful, balanced hybrid." },
  { name: "Tropicana Cookies", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Girl Scout Cookies x Tangie. Orange citrus cookie; uplifting, creative mood." },
  { name: "Motor Breath", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chem D x SFV OG Kush. Gas and earth; powerful sedative body lock." },
  { name: "Biscotti", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Gelato #25 x Girl Scout Cookies x Gorilla Glue. Sweet cookie dough; calm, cozy high." },
  { name: "MAC", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Alien Cookies x (Colombian x Starfighter). Citrus cream; balanced euphoric clarity." },
  { name: "London Pound Cake", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Sunset Sherbet x unknown parent. Berry-lemon cake; relaxed, happy mood." },
  { name: "Cereal Milk", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Y Life x Snowman. Creamy sweet milk; balanced uplifting relaxation." },
  { name: "Jealousy", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Gelato #41 x Sherbert Bx1. Creamy orange gas; mellow euphoria." },
  { name: "Slurricane", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: Do-Si-Dos x Purple Punch. Grape berry cream; heavy sedative indica." },
  { name: "Sundae Driver", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Fruity Pebbles OG x Grape Pie. Chocolate cherry cream; balanced relaxed mood." },
  { name: "Rainbow Belts", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Zkittlez x Moonbow. Fruity candy mix; euphoric happy high." },
  { name: "Maui Wowie", type: "sativa" as const, terp_profile: ["limonene" as const, "pinene" as const], description: "Lineage: Hawaiian landrace. Tropical pineapple; energetic island vibes." },
  { name: "Acapulco Gold", type: "sativa" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: Mexican landrace. Burnt toffee honey; uplifting motivational energy." },
  { name: "Panama Red", type: "sativa" as const, terp_profile: ["myrcene" as const, "limonene" as const], description: "Lineage: Panamanian landrace. Earthy citrus spice; clear cerebral focus." },
  { name: "Lamb's Bread", type: "sativa" as const, terp_profile: ["pinene" as const, "caryophyllene" as const], description: "Lineage: Jamaican landrace. Herbal cheese; energizing creative uplift." },
  { name: "Chocolope", type: "sativa" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chocolate Thai x Cannalope Haze. Chocolate coffee; dreamy euphoric energy." },
  { name: "Candyland", type: "sativa" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Granddaddy Purple x Bay Platinum Cookies. Sweet candy citrus; upbeat social energy." },
  { name: "Ghost Train Haze", type: "sativa" as const, terp_profile: ["limonene" as const, "pinene" as const], description: "Lineage: Ghost OG x Neville's Wreck. Citrus pine diesel; powerful cerebral rush." },
  { name: "Sour Tangie", type: "sativa" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: East Coast Sour Diesel x Tangie. Sour tangerine; creative energetic buzz." },
  { name: "Electric Lemonade", type: "sativa" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Lemon Thai x GMO. Zesty lemon sugar; bright focused energy." },
  { name: "Golden Goat", type: "hybrid" as const, terp_profile: ["limonene" as const, "pinene" as const], description: "Lineage: Hawaiian x Romulan x Island Sweet Skunk. Tropical citrus spice; happy uplifting mood." },
  { name: "Space Queen", type: "hybrid" as const, terp_profile: ["pinene" as const, "caryophyllene" as const], description: "Lineage: Romulan x Cinderella 99. Cherry vanilla spice; cerebral dreamy euphoria." },
  { name: "Cosmic Queen", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: Space Queen x Afghani. Fruity grape citrus; balanced spacey relaxation." },
  { name: "Stardawg", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chemdawg 4 x Tres Dawg. Diesel earth pine; potent uplifting hybrid." },
  { name: "Black Widow", type: "hybrid" as const, terp_profile: ["pinene" as const, "myrcene" as const], description: "Lineage: Brazilian x South Indian. Pungent pine earth; balanced powerful high." },
  { name: "White Russian", type: "indica" as const, terp_profile: ["myrcene" as const, "pinene" as const], description: "Lineage: White Widow x AK-47. Woody citrus pine; relaxing sedative body feel." },
  { name: "Blackberry Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Afghani x Blackberry. Dark berry earth; deeply relaxing body stone." },
  { name: "Blueberry Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const], description: "Lineage: Blueberry x OG Kush. Sweet berry pine; soothing full-body calm." },
  { name: "Raspberry Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: Hindu Kush x Raspberry. Tart berry earth; mellow sleepy indica." },
  { name: "Watermelon Zkittlez", type: "indica" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Zkittlez x Watermelon. Fruity melon candy; happy sedative indica." },
  { name: "Peach Crescendo", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Chem Dawg x I-95 x Mandarin Cookies. Peach citrus gas; balanced uplifting buzz." },
  { name: "Peanut Butter Breath", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Do-Si-Dos x Mendobreath. Nutty earth; relaxed sedative hybrid." },
  { name: "Kush Mints", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Bubba Kush x Animal Mints. Minty cookie gas; balanced euphoric calm." },
  { name: "Mendo Breath", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: OG Kush Breath x Mendo Montage. Vanilla caramel earth; heavy sedative body." },
  { name: "Animal Cookies", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Girl Scout Cookies x Fire OG. Sour diesel cookie; potent relaxing high." },
  { name: "Lava Cake", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Thin Mint Cookies x Grape Pie. Chocolate mint earth; powerful sedative stone." },
  { name: "Papaya", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const], description: "Lineage: Citral #13 x Ice #2. Tropical mango papaya; relaxing sleepy indica." },
  { name: "Lemon Meringue", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Lemon Skunk x Cookies x Sour Diesel. Lemon cream pie; uplifting balanced mood." },
  { name: "Bacio Gelato", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Sunset Sherbert x Girl Scout Cookies. Sweet berry cream; euphoric calming high." },
  { name: "Jungle Cake", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Wedding Cake x White Fire #43. Vanilla cream earth; relaxed happy buzz." },
  { name: "Sherbacio", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Sunset Sherbert x Gelato. Orange sherbet cream; mellow euphoric feel." },
  { name: "Georgia Pie", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const], description: "Lineage: Gellati x Kush Mints. Peach cobbler spice; balanced relaxing high." },
  { name: "Apples and Bananas", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const], description: "Lineage: Platinum Cookies x Granddaddy Purple x Blue Power. Fruity candy; euphoric calm mood." },
  { name: "Chem #4", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chemdawg phenotype. Diesel pine fuel; potent cerebral uplift." },
  { name: "Chem '91", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const], description: "Lineage: Chemdawg phenotype. Skunky gas earth; powerful heady high." },
  { name: "Motorbreath #15", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Chem D x SFV OG Kush. Gas fuel earth; heavy sedative body lock." },
  { name: "Orange Creamsicle", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const], description: "Lineage: Orange Crush x Juicy Fruit. Sweet orange cream; happy uplifting feel." },
  { name: "Cherry Diesel", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Cherry OG x Turbo Diesel. Cherry gas fuel; balanced energetic mood." },
  { name: "Berry White", type: "hybrid" as const, terp_profile: ["myrcene" as const, "pinene" as const], description: "Lineage: Blueberry x White Widow. Sweet berry pine; relaxed mellow high." },
  { name: "Cherry Bomb", type: "sativa" as const, terp_profile: ["caryophyllene" as const, "limonene" as const], description: "Lineage: Cherry Thai x Cherry AK-47. Tart cherry spice; energetic creative buzz." },
  { name: "9 Pound Hammer", type: "indica" as const, terp_profile: ["myrcene" as const, "limonene" as const, "caryophyllene" as const], description: "Lineage: Gooberry x Hells OG x Jack the Ripper. Grape-citrus and earth; heavy, sleep-ready indica stone." },
  { name: "Hindu Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "limonene" as const, "caryophyllene" as const], description: "Lineage: Hindu Kush landrace. Sweet pine and hashy earth; classic, steady full-body calm." },
  { name: "Harlequin", type: "sativa" as const, terp_profile: ["myrcene" as const, "pinene" as const, "caryophyllene" as const], description: "Lineage: Colombian Gold x Thai x Swiss landrace. Herbal citrus; clear, CBD-forward daytime ease." },
  { name: "Pure Michigan", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Oreoz x Mendo Breath F2. Earthy sweet cream with citrus-pine; heavy, relaxing hybrid melt." },
  { name: "Blue Cheese", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: UK Cheese x Blueberry. Funky cheese and berries; calm, stoney indica comfort." },
  { name: "NYC Sour Diesel", type: "sativa" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Sour Diesel family. Sharp fuel and lemon zest; racy, city-bright head buzz." },
  { name: "Super Boof", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: Black Cherry Punch x Tropicana Cookies. Tangy cherry-orange; strong, floaty hybrid stone." },
  { name: "Super Skunk", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Skunk #1 backcross. Classic skunk funk and sweet spice; balanced old-school high." },
  { name: "Island Sweet Skunk", type: "sativa" as const, terp_profile: ["myrcene" as const, "limonene" as const, "pinene" as const], description: "Lineage: Skunk family. Tropical citrus and sweet funk; bright, focused island energy." },
  { name: "Grapefruit", type: "sativa" as const, terp_profile: ["limonene" as const, "myrcene" as const, "caryophyllene" as const], description: "Lineage: Cinderella 99 line. Ruby grapefruit sweetness; zippy, mood-lifting headspace." },
  { name: "Laughing Buddha", type: "sativa" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Thai x Jamaican. Spicy herbal citrus; giggly, social sativa vibe." },
  { name: "Red Headed Stranger", type: "sativa" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "pinene" as const], description: "Lineage: William's Wonder x Haze. Spiced citrus and herb; alert, creative daytime ride." },
  { name: "Schrom", type: "sativa" as const, terp_profile: ["limonene" as const, "myrcene" as const, "pinene" as const], description: "Lineage: Silver Haze family. Lemon-lime and pine; clear, buzzy head lift." },
  { name: "Kali Mist", type: "sativa" as const, terp_profile: ["myrcene" as const, "limonene" as const, "caryophyllene" as const], description: "Lineage: Haze-forward blend. Dry spice and herb; classic cerebral sativa clarity." },
  { name: "Pine Tar", type: "indica" as const, terp_profile: ["myrcene" as const, "pinene" as const, "caryophyllene" as const], description: "Lineage: Pakistani Kush line. Rich pine resin and earth; heavy, old-school body stone." },
  { name: "Querkle", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Purple Urkle x Space Queen. Grape-berry candy; cozy, dreamy indica tilt." },
  { name: "Alien Kush", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Alien Dawg lineage. Pine, spice, and gas; buzzy but relaxing cosmic hybrid." },
  { name: "Space Cake", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: GSC x Snow Lotus. Frosted dough and earth; dense, floaty full-body high." },
  { name: "Rocket Fuel", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: Jet Fuel OG x Face Off OG. Sharp gas and pine; strong, knockout evening hybrid." },
  { name: "Alien Dawg", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "pinene" as const], description: "Lineage: Alien Technology x Chemdawg. Earthy chem and pine; sedating, weighty body calm." },
  { name: "Star Child", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const, "caryophyllene" as const], description: "Lineage: spacey hybrid line. Bright citrus and sweet fruit; floaty, euphoric headspace." },
  { name: "Stargazer", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "humulene" as const], description: "Lineage: indica-dominant hybrid. Spiced earth and berry; heavy, contemplative couch mode." },
  { name: "Moon Cookies", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: Cookies family cross. Sweet dough and gas; dense, spacey relaxation." },
  { name: "Space Candy", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Cotton Candy x Space Queen. Sour candy fruit; upbeat, heady hybrid." },
  { name: "Space Dawg", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Chemdawg 4 x Space Queen. Funky chem-fruit mix; potent, stoney cruise." },
  { name: "Alien Abduction", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Alien OG line. Skunky pine and gas; intense, head-heavy hybrid." },
  { name: "Alien Bubba", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "humulene" as const], description: "Lineage: Bubba Kush x Alien Kush. Earthy coffee and kush; deeply sedating nightcap." },
  { name: "Alien Asshat", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: Alien family hybrid. Loud funk and citrus; wild, spacey high with a goofy edge." },
  { name: "Pineapple Chunk", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Cheese x Skunk #1 x Pineapple. Funky pineapple and earth; strong, relaxing hybrid." },
  { name: "Critical Mass", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "humulene" as const], description: "Lineage: Afghani x Skunk #1. Musky skunk and wood; dense, sleepy indica." },
  { name: "White Rhino", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "pinene" as const], description: "Lineage: White Widow x North American indica. Pungent wood and spice; heavy, slow-body stone." },
  { name: "Afghan Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "pinene" as const], description: "Lineage: Afghani landrace. Hashy earth and pine; classic, sedating body stone." },
  { name: "Platinum OG", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "limonene" as const], description: "Lineage: Master Kush x OG Kush x Purps. Heavy gas and kush; dense, sleepy relaxation." },
  { name: "Skywalker", type: "hybrid" as const, terp_profile: ["myrcene" as const, "pinene" as const, "caryophyllene" as const], description: "Lineage: Blueberry x Mazar. Berry, pine, and earth; mellow galactic calm." },
  { name: "Star Dawg", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: Chemdawg 4 x Tres Dawg. Diesel funk; uplifting, spacey hybrid buzz." },
  { name: "Kosher Kush", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "limonene" as const], description: "Lineage: OG Kush family. Spicy pine and earth; heavy, couchy night strain." },
  { name: "LA Kush Cake", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: Kush Mints x Wedding Cake. Sweet dough and gas; calm, dessert-like stone." },
  { name: "Wedding Pie", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "linalool" as const], description: "Lineage: Wedding Cake x Grape Pie. Sugary grape and vanilla; cozy, blissful hybrid." },
  { name: "GMO Cookies", type: "indica" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: Girl Scout Cookies x Chemdawg. Garlic, gas, and cookie dough; powerful couch-lock." },
  { name: "Garlic Breath", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "humulene" as const], description: "Lineage: GMO x Mendo Breath. Savory garlic and earth; slow, stoney relaxation." },
  { name: "Donny Burger", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "limonene" as const], description: "Lineage: GMO x Larry OG. Funky garlic gas; heavy, mind-warping chill." },
  { name: "Miracle Alien Cookies", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Alien Cookies x Starfighter. Citrus cream and spice; euphoric, spacey uplift." },
  { name: "MAC 1", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "humulene" as const], description: "Lineage: Miracle Alien Cookies selection. Creamy citrus and gas; balanced, heady clarity." },
  { name: "Triangle Kush", type: "indica" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "limonene" as const], description: "Lineage: Florida OG. Pungent earth and pine; slow, heavy kush sedation." },
  { name: "SFV OG", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: OG Kush variant. Lemon-pine fuel; strong, chest-relaxing OG high." },
  { name: "Larry OG", type: "hybrid" as const, terp_profile: ["limonene" as const, "pinene" as const, "caryophyllene" as const], description: "Lineage: OG Kush cut. Lemon pledge and pine; relaxed but functional OG calm." },
  { name: "Do-Si-Dos 22", type: "indica" as const, terp_profile: ["caryophyllene" as const, "linalool" as const, "myrcene" as const], description: "Lineage: Do-Si-Dos phenotype. Sweet cookie spice; deep, tranquil body ease." },
  { name: "Purple Urkle", type: "indica" as const, terp_profile: ["myrcene" as const, "linalool" as const, "caryophyllene" as const], description: "Lineage: Northern California purple line. Grape soda and skunk; dreamy, sedating night strain." },
  { name: "Shishkaberry", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "linalool" as const], description: "Lineage: DJ Short Blueberry x Afghan. Sweet berry jam; mellow, sleepy body buzz." },
  { name: "Critical Kush", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "humulene" as const], description: "Lineage: Critical Mass x OG Kush. Skunky pine and spice; very heavy, slow-moving calm." },
  { name: "Pineapple Upside Down Cake", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const, "caryophyllene" as const], description: "Lineage: Pineapple Trainwreck x Cookie Monster. Sweet baked pineapple; relaxed, happy float." },
  { name: "Lemon Tree", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Lemon Skunk x Sour Diesel. Loud lemon peel and gas; upbeat, stoney headspace." },
  { name: "Lemon Diesel", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: California Sour x Lost Coast OG. Sour lemon fuel; relaxed but hazy high." },
  { name: "Key Lime Pie", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "linalool" as const], description: "Lineage: GSC phenotype. Lime zest and cream; dense, dreamy hybrid calm." },
  { name: "Gorilla Cookies", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const, "limonene" as const], description: "Lineage: Thin Mint GSC x Gorilla Glue. Doughy gas; strong, glued-but-smiling high." },
  { name: "Strawberry Banana", type: "hybrid" as const, terp_profile: ["myrcene" as const, "limonene" as const, "caryophyllene" as const], description: "Lineage: Banana Kush x Bubble Gum. Strawberry-banana smoothie; chill, euphoric buzz." },
  { name: "Banana Split", type: "hybrid" as const, terp_profile: ["limonene" as const, "myrcene" as const, "caryophyllene" as const], description: "Lineage: Tangie x Banana Sherbet. Dessert-sweet citrus and banana; easygoing, playful mood." },
  { name: "Banana Punch", type: "indica" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: Banana OG x Purple Punch. Creamy fruit punch; relaxing, drowsy indica tilt." },
  { name: "Ice Cream Man", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "humulene" as const], description: "Lineage: Jet Fuel Gelato x Legend Orange Apricot. Sweet cream and gas; smooth, mellow euphoria." },
  { name: "Cookie Dough", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "humulene" as const, "limonene" as const], description: "Lineage: GSC line. Raw cookie dough sweetness; dense, relaxing full-body high." },
  { name: "Vanilla Frosting", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "linalool" as const], description: "Lineage: Humboldt Frost OG x Humboldt Gelato. Frosted vanilla and fuel; calm, euphoric haze." },
  { name: "Mint Chocolate Chip", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "limonene" as const, "myrcene" as const], description: "Lineage: Mystery Cookies x Green Ribbon BX. Minty chocolate and earth; balanced, cool-headed chill." },
  { name: "Blueberry OG", type: "hybrid" as const, terp_profile: ["myrcene" as const, "pinene" as const, "caryophyllene" as const], description: "Lineage: Blueberry x OG Kush. Sweet berry and pine; heavy but happy hybrid stone." },
  { name: "Cherry Garcia", type: "hybrid" as const, terp_profile: ["myrcene" as const, "caryophyllene" as const, "limonene" as const], description: "Lineage: 3X Crazy x Animal Cookies. Cherry ice cream vibes; chill, dreamy euphoria." },
  { name: "Citrus Sap", type: "hybrid" as const, terp_profile: ["limonene" as const, "caryophyllene" as const, "myrcene" as const], description: "Lineage: Gorilla Glue #4 x Tangie. Sharp orange fuel; sticky, uplifting head high." },
  { name: "Headbanger", type: "hybrid" as const, terp_profile: ["caryophyllene" as const, "myrcene" as const, "limonene" as const], description: "Lineage: Sour Diesel x Biker Kush. Sour fuel and kush; intense, ringing head buzz." }
] as const;

export async function seedDemoStrains(): Promise<Strain[]> {
  console.log('[SeedStrains] Starting demo strain generation...');
  const strains: Strain[] = [];
  for (const data of DEMO_STRAINS_DATA) {
    try {
      const strain = createStrain(data.name, data.type, { terp_profile: [...data.terp_profile], description: data.description, source: "developer" });
      await writeStrainJSON(strain);
      strains.push(strain);
      console.log(`[SeedStrains] ✓ Created ${data.name} (${strain.strain_id})`);
    } catch (error) {
      console.error(`[SeedStrains] Failed to create ${data.name}:`, error);
    }
  }
  console.log(`[SeedStrains] Complete! Generated ${strains.length} strains.`);
  return strains;
}
